### ISSUE TITLE
🚀 Initial Project Setup and Functional Prototype

### ISSUE THREAD

**Issue by dhcgn** [dhcgn/go-obsidian-ai-sum#1]
## ✅ Goal

Build a Go-based CLI tool that:

- Accepts a file or folder as input
- Recursively parses Markdown files with Obsidian-style YAML frontmatter
- Generates a summary using OpenAI (via API)
- Writes the summary into `summarize_ai` and `summarize_ai_hash` fields in the frontmatter
- Supports flags to override summaries, prompts, and API key
- Prepares for future AI provider abstraction

---

## 📁 Project Structure

```
go-obsidian-ai-sum/
├── cmd/
│   └── root.go               # Cobra CLI entry point
├── internal/
│   ├── summarizer/           # Logic for calling AI APIs
│   ├── frontmatter/          # YAML parsing and writing
│   └── fswalker/             # File and directory traversal
├── testdata/                 # Sample files for test runs
├── .github/
│   └── copilot-instructions.md
├── go.mod
└── main.go
```

---

### 🔧 1. CLI Setup (using Cobra)

- [ ] `--path`: path to file or folder
- [ ] `--api-key`: override environment variable
- [ ] `--prompt`: override default prompt
- [ ] `--override`: allow re-summarizing files

### 📄 2. YAML Frontmatter Handling

- [ ] Parse frontmatter from `.md` files
- [ ] Inject new or update existing `summarize_ai` and `summarize_ai_hash`
- [ ] Ensure structure and indentation are preserved

### 📂 3. File System Support

- [ ] Read a single file or all Markdown files in a folder recursively
- [ ] Filter out non-`.md` files
- [ ] Skip files that already have `summarize_ai`, unless `--override` is set

### 🤖 4. OpenAI Summarization

- [ ] Load prompt from flag or use a sane default
- [ ] Compute hash of prompt (first 16 hex chars of SHA256)
- [ ] Use OpenAI API to generate summary
- [ ] Inject summary and hash into YAML frontmatter

### 🔌 5. Pluggable AI Provider Interface

- [ ] Define an interface like `Summarizer` with method `Summarize(text, prompt string) (string, error)`
- [ ] Implement OpenAI-based `Summarizer` as default

---

## 🧪 Testing

- [ ] Unit tests for frontmatter parsing & writing
- [ ] Tests for summarization hash calculation
- [ ] Integration test: input file → summarized file
- [ ] Add a sample Obsidian file in `testdata/`

---

### Input:

```yaml
---
title: A New Hope
year: 1977
favorite: true
cast:
  - Mark Hamill
  - Harrison Ford
  - Carrie Fisher
---
The galaxy is in turmoil...
```

### Output (after running tool):

```yaml
---
title: A New Hope
year: 1977
favorite: true
summarize_ai: A classic space opera where rebels fight the evil empire.
summarize_ai_hash: 3f5a9c1b7e2d1a0f
cast:
  - Mark Hamill
  - Harrison Ford
  - Carrie Fisher
---
```

---

## 🧹 Cleanup

- [ ] `.editorconfig` or `.gofmt` for formatting
- [ ] Add `.gitignore`
- [ ] License file (MIT)
