### ISSUE TITLE
Feature Request: Add Timestamp and Filter for Outdated Files

### ISSUE THREAD

**Issue by dhcgn** [dhcgn/go-obsidian-ai-sum#4]
#### **Problem**
Currently, the tool processes all files, even if they are up-to-date. This leads to unnecessary re-summarizations of files that have not changed, increasing processing time and API costs. Another Obsidian extension already tracks file changes using `created` and `updated` timestamps in the frontmatter, which can be leveraged to optimize this tool.

#### **Proposed Solution**
1. **Add a Timestamp Field to the Frontmatter**  
   Add a new `summarize_ai_updated` field to store the timestamp of the last summarization.  
   Example:  
   ```yaml
   ---
   summarize_ai: Test summary
   summarize_ai_updated: 2025-03-23T10:43
   summarize_ai_hash: TestHash
   summarize_ai_tags:
     - tag1
     - tag2
     - tag3
   ---
   ```

2. **Filter Outdated Files**  
   Compare the `updated` field (tracked by the other Obsidian extension) with the `summarize_ai_updated` field. Only files where `updated > summarize_ai_updated` should be re-summarized. This ensures that only outdated files are processed.

3. **Implementation Steps**:  
   - **Update Logic**: Add logic to check the file's `updated` timestamp against `summarize_ai_updated` before summarizing.  
   - **Fallback**: If `summarize_ai_updated` is missing, treat the file as outdated and process it.  
   - **Optional Flag**: Allow a flag like `--force` to override this behavior and re-summarize all files regardless of timestamps.

#### **Benefits**
- Reduces unnecessary API calls, saving costs.
- Speeds up processing by skipping up-to-date files.
- Integrates seamlessly with existing metadata tracked by Obsidian extensions.

#### **Example Frontmatter with Changes**
**Existing Metadata (tracked by another extension):**
```yaml
---
created: 2025-02-23T10:40
updated: 2025-03-29T07:53
---
```

**Proposed Updated Frontmatter:**
```yaml
---
summarize_ai: Test summary
summarize_ai_updated: 2025-03-29T07:53
summarize_ai_hash: TestHash
summarize_ai_tags:
  - tag1
  - tag2
  - tag3
---
```

#### **Affected Components**
- `internal/frontmatter/frontmatter.go`: Update parsing logic to handle the new `summarize_ai_updated` field.
- `internal/fswalker/fswalker.go`: Add filtering logic for outdated files.
- `cmd/root.go`: Integrate the filtering logic into the CLI workflow.

#### **Additional Context**
This enhancement aligns with the existing structure of the tool and leverages the `updated` field already tracked by other extensions. It ensures efficient processing and better integration with Obsidian workflows.
